import { Severity } from '../types/index.js';
export type WordEntry = { word: string; severity: Severity; language: string };
export const defaultWords: WordEntry[] = [
  { word: 'كلب', severity: 'MILD', language: 'ar' },
  { word: 'غبي', severity: 'MILD', language: 'ar' },
  { word: 'حمار', severity: 'MILD', language: 'ar' },
  { word: 'تافه', severity: 'MILD', language: 'ar' },
  { word: 'حيوان', severity: 'MILD', language: 'ar' },
  { word: 'هامل', severity: 'MILD', language: 'ar-ma' },
  { word: 'عبيط', severity: 'MILD', language: 'ar-eg' },
  { word: 'اهبل', severity: 'MILD', language: 'ar-gulf' },
  { word: 'خايس', severity: 'MILD', language: 'ar-gulf' },
  { word: 'سخيف', severity: 'MILD', language: 'ar' },
  { word: 'لوح', severity: 'MILD', language: 'ar-lev' },
  { word: 'غشيم', severity: 'MILD', language: 'ar-gulf' },
  { word: 'ثور', severity: 'MILD', language: 'ar' },
  { word: 'دب', severity: 'MILD', language: 'ar' },
  { word: 'رخم', severity: 'MILD', language: 'ar-eg' },
  { word: 'بارد', severity: 'MILD', language: 'ar' },
  { word: 'زق', severity: 'MILD', language: 'ar-lev' },
  { word: 'مجنون', severity: 'MILD', language: 'ar' },
  { word: 'بهيم', severity: 'MILD', language: 'ar-eg' },
  { word: 'جحش', severity: 'MILD', language: 'ar-lev' },
  { word: 'زفت', severity: 'MEDIUM', language: 'ar' },
  { word: 'قذر', severity: 'MEDIUM', language: 'ar' },
  { word: 'حقير', severity: 'MEDIUM', language: 'ar' },
  { word: 'وسخ', severity: 'MEDIUM', language: 'ar' },
  { word: 'زبالة', severity: 'MEDIUM', language: 'ar' },
  { word: 'سافل', severity: 'MEDIUM', language: 'ar' },
  { word: 'منحط', severity: 'MEDIUM', language: 'ar' },
  { word: 'نذل', severity: 'MEDIUM', language: 'ar-gulf' },
  { word: 'واطي', severity: 'MEDIUM', language: 'ar-eg' },
  { word: 'خسيس', severity: 'MEDIUM', language: 'ar' },
  { word: 'نتن', severity: 'MEDIUM', language: 'ar' },
  { word: 'معفن', severity: 'MEDIUM', language: 'ar-eg' },
  { word: 'تيس', severity: 'MEDIUM', language: 'ar-gulf' },
  { word: 'بغل', severity: 'MEDIUM', language: 'ar' },
  { word: 'خروف', severity: 'MEDIUM', language: 'ar' },
  { word: 'ساقط', severity: 'MEDIUM', language: 'ar-iq' },
  { word: 'قندرة', severity: 'MEDIUM', language: 'ar-iq' },
  { word: 'ورع', severity: 'MEDIUM', language: 'ar-gulf' },
  { word: 'هيس', severity: 'MEDIUM', language: 'ar-eg' },
  { word: 'عرة', severity: 'MEDIUM', language: 'ar-eg' },
  { word: 'يلعن', severity: 'MEDIUM', language: 'ar' },
  { word: 'ناقص', severity: 'MEDIUM', language: 'ar' },
  { word: 'خرا', severity: 'MEDIUM', language: 'ar-lev' },
  { word: 'خنا', severity: 'MEDIUM', language: 'ar-ma' },
  { word: 'طحان', severity: 'MEDIUM', language: 'ar-dz' },
  { word: 'رخيص', severity: 'MEDIUM', language: 'ar' },
  { word: 'جرثومة', severity: 'MEDIUM', language: 'ar' },
  { word: 'حثالة', severity: 'MEDIUM', language: 'ar' },
  { word: 'خول', severity: 'SEVERE', language: 'ar-eg' },
  { word: 'عرص', severity: 'SEVERE', language: 'ar-eg' },
  { word: 'معرص', severity: 'SEVERE', language: 'ar-eg' },
  { word: 'خنيث', severity: 'SEVERE', language: 'ar-gulf' },
  { word: 'مخنث', severity: 'SEVERE', language: 'ar-sa' },
  { word: 'ديوث', severity: 'SEVERE', language: 'ar-sa' },
  { word: 'قواد', severity: 'SEVERE', language: 'ar-gulf' },
  { word: 'زامل', severity: 'SEVERE', language: 'ar-ma' },
  { word: 'زامولة', severity: 'SEVERE', language: 'ar-tn' },
  { word: 'طقعان', severity: 'SEVERE', language: 'ar-gulf' },
  { word: 'خكري', severity: 'SEVERE', language: 'ar-sa' },
  { word: 'علوق', severity: 'SEVERE', language: 'ar-iq' },
  { word: 'فرخ', severity: 'SEVERE', language: 'ar-eg' },
  { word: 'سالب', severity: 'SEVERE', language: 'ar' },
  { word: 'موجب', severity: 'SEVERE', language: 'ar' },
  { word: 'ابن كلب', severity: 'SEVERE', language: 'ar' },
  { word: 'ابن وسخة', severity: 'SEVERE', language: 'ar' },
  { word: 'يا ابن', severity: 'SEVERE', language: 'ar' },
  { word: 'ابن حرام', severity: 'SEVERE', language: 'ar' },
  { word: 'يلعن ابوك', severity: 'SEVERE', language: 'ar' },
  { word: 'يلعن امك', severity: 'SEVERE', language: 'ar' },
  { word: 'كس امك', severity: 'SEVERE', language: 'ar-lev' },
  { word: 'كسمك', severity: 'SEVERE', language: 'ar-eg' },
  { word: 'لبوة', severity: 'SEVERE', language: 'ar-eg' },
  { word: 'عاهر', severity: 'SEVERE', language: 'ar' },
  { word: 'فاجر', severity: 'SEVERE', language: 'ar' },
  { word: 'ساقطة', severity: 'SEVERE', language: 'ar' },
  { word: 'وسخة', severity: 'SEVERE', language: 'ar' },
  { word: 'نغل', severity: 'SEVERE', language: 'ar-iq' },
  { word: 'قحب', severity: 'SEVERE', language: 'ar' },
  { word: 'متناك', severity: 'EXTREME', language: 'ar' },
  { word: 'متناكة', severity: 'EXTREME', language: 'ar' },
  { word: 'منيوك', severity: 'EXTREME', language: 'ar-gulf' },
  { word: 'شرموط', severity: 'EXTREME', language: 'ar-eg' },
  { word: 'شرموطة', severity: 'EXTREME', language: 'ar-eg' },
  { word: 'قحبة', severity: 'EXTREME', language: 'ar' },
  { word: 'قحبه', severity: 'EXTREME', language: 'ar-sa' },
  { word: 'كس', severity: 'EXTREME', language: 'ar' },
  { word: 'كس اختك', severity: 'EXTREME', language: 'ar-lev' },
  { word: 'كس امك', severity: 'EXTREME', language: 'ar' },
  { word: 'نيك', severity: 'EXTREME', language: 'ar' },
  { word: 'انيكك', severity: 'EXTREME', language: 'ar' },
  { word: 'انيك امك', severity: 'EXTREME', language: 'ar' },
  { word: 'نيك امك', severity: 'EXTREME', language: 'ar' },
  { word: 'احا', severity: 'EXTREME', language: 'ar-eg' },
  { word: 'عرص كبير', severity: 'EXTREME', language: 'ar-eg' },
  { word: 'يا قحبة', severity: 'EXTREME', language: 'ar' },
  { word: 'يا شرموطة', severity: 'EXTREME', language: 'ar' },
  { word: 'يا متناك', severity: 'EXTREME', language: 'ar' },
  { word: 'sharmota', severity: 'EXTREME', language: 'ar-fra' },
  { word: 'kahba', severity: 'EXTREME', language: 'ar-fra' },
  { word: 'nik', severity: 'EXTREME', language: 'ar-fra' },
  { word: 'kos', severity: 'EXTREME', language: 'ar-fra' },
  { word: '3ars', severity: 'SEVERE', language: 'ar-fra' },
  { word: '5awal', severity: 'SEVERE', language: 'ar-fra' },
  { word: 'zamel', severity: 'SEVERE', language: 'ar-fra' },
  { word: '9ahba', severity: 'EXTREME', language: 'ar-fra' },
  { word: 'mnayek', severity: 'EXTREME', language: 'ar-fra' },
  { word: 'stupid', severity: 'MILD', language: 'en' },
  { word: 'idiot', severity: 'MILD', language: 'en' },
  { word: 'dumb', severity: 'MILD', language: 'en' },
  { word: 'loser', severity: 'MILD', language: 'en' },
  { word: 'moron', severity: 'MILD', language: 'en' },
  { word: 'dumbass', severity: 'MEDIUM', language: 'en' },
  { word: 'jackass', severity: 'MEDIUM', language: 'en' },
  { word: 'piss', severity: 'MEDIUM', language: 'en' },
  { word: 'shit', severity: 'MEDIUM', language: 'en' },
  { word: 'shitty', severity: 'MEDIUM', language: 'en' },
  { word: 'asshole', severity: 'SEVERE', language: 'en' },
  { word: 'bitch', severity: 'SEVERE', language: 'en' },
  { word: 'bastard', severity: 'SEVERE', language: 'en' },
  { word: 'dick', severity: 'SEVERE', language: 'en' },
  { word: 'dickhead', severity: 'SEVERE', language: 'en' },
  { word: 'slut', severity: 'SEVERE', language: 'en' },
  { word: 'whore', severity: 'SEVERE', language: 'en' },
  { word: 'cunt', severity: 'EXTREME', language: 'en' },
  { word: 'fuck', severity: 'EXTREME', language: 'en' },
  { word: 'fucking', severity: 'EXTREME', language: 'en' },
  { word: 'fucker', severity: 'EXTREME', language: 'en' },
  { word: 'motherfucker', severity: 'EXTREME', language: 'en' },
  { word: 'nigger', severity: 'EXTREME', language: 'en' },
  { word: 'nigga', severity: 'EXTREME', language: 'en' },
  { word: 'fag', severity: 'EXTREME', language: 'en' },
  { word: 'faggot', severity: 'EXTREME', language: 'en' },
  { word: 'kys', severity: 'EXTREME', language: 'en' },
  { word: 'kill yourself', severity: 'EXTREME', language: 'en' },
];
export const defaultWhitelist: string[] = ['مستقبل','مستقبلي','كتاب','كتب','حمار وحشي','hello','classic','assistant','مستوى','تحليل','شمس','قمر'];
